/**
 * Donnees de demonstration pour le template visuel.
 * A remplacer par les appels au microservice Admission-service
 * (features/admission/api sera le point d'entree reseau).
 */
import {
  Admission,
  AdmissionDocumentType,
  AdmissionPayerType,
  AdmissionStatus,
  AdmissionType,
  Relationship,
} from "../types";

export const mockAdmissions: Admission[] = [
  {
    id: "adm-001",
    admissionNumber: "ADM-2026-00841",
    patientId: "pat-1001",
    numeroPatient: "DOS-018245",
    patientName: "Aya Koffi",
    sex: "F",
    age: 34,
    doctorName: "Dr. Fabrice N'Guessan",
    department: "Cardiologie",
    admissionType: AdmissionType.INPATIENT,
    admissionStatus: AdmissionStatus.ADMITTED,
    reason: "Douleurs thoraciques, suspicion d'angor instable",
    admissionDate: "2026-08-18T08:15:00",
    expectedDischarge: "2026-08-22T12:00:00",
    documents: [
      { id: "d1", documentType: AdmissionDocumentType.PIECE_IDENTIE, fileName: "cni_aya_koffi.pdf", size: "412 Ko", uploadedAt: "2026-08-18T08:20:00" },
      { id: "d2", documentType: AdmissionDocumentType.CARTE_ASSURANCE, fileName: "carte_cnps.jpg", size: "1.1 Mo", uploadedAt: "2026-08-18T08:21:00" },
    ],
    companions: [
      { id: "c1", fullName: "Jean Koffi", relationship: Relationship.HUSBAND, phone: "+225 07 08 09 10 11" },
    ],
    payers: [
      { id: "p1", payerType: AdmissionPayerType.INSURANCE, name: "CNPS", policyNumber: "CNPS-99182", coveragePercentage: 80, coverageLimit: 2000000, validUntil: "2026-12-31" },
      { id: "p2", payerType: AdmissionPayerType.PATIENT, name: "Aya Koffi", coveragePercentage: 20 },
    ],
    encounter: { encounterNumber: "ENC-2026-00841", encounterStatus: "En cours", currentDepartment: "Cardiologie", currentRoom: "C-204", currentBed: "Lit 2", startDate: "2026-08-18T08:30:00" },
    createdBy: "Accueil - S. Ibaka",
  },
  {
    id: "adm-002",
    admissionNumber: "ADM-2026-00842",
    patientId: "pat-1002",
    numeroPatient: "DOS-018246",
    patientName: "Moussa Traoré",
    sex: "M",
    age: 58,
    doctorName: "Dr. Céline Assi",
    department: "Urgences",
    admissionType: AdmissionType.EMERGENCY,
    admissionStatus: AdmissionStatus.PENDING,
    reason: "Traumatisme crânien suite à un accident de la voie publique",
    admissionDate: "2026-08-18T09:42:00",
    documents: [],
    companions: [{ id: "c2", fullName: "Fatou Traoré", relationship: Relationship.DAUTHER, phone: "+225 05 66 77 88 99" }],
    payers: [{ id: "p3", payerType: AdmissionPayerType.PATIENT, name: "Moussa Traoré", coveragePercentage: 100 }],
    createdBy: "Accueil - S. Ibaka",
  },
  {
    id: "adm-003",
    admissionNumber: "ADM-2026-00843",
    patientId: "pat-1003",
    numeroPatient: "DOS-017903",
    patientName: "Grace Mensah",
    sex: "F",
    age: 27,
    doctorName: "Dr. Fabrice N'Guessan",
    department: "Maternité",
    admissionType: AdmissionType.INPATIENT,
    admissionStatus: AdmissionStatus.PRE_ADMITTED,
    reason: "Suivi de grossesse — admission programmée",
    admissionDate: "2026-08-19T07:00:00",
    expectedDischarge: "2026-08-21T10:00:00",
    documents: [{ id: "d3", documentType: AdmissionDocumentType.ORDONNANCE, fileName: "ordonnance.pdf", size: "220 Ko", uploadedAt: "2026-08-17T16:00:00" }],
    companions: [],
    payers: [{ id: "p4", payerType: AdmissionPayerType.COMPANY, name: "SIB Assurances", policyNumber: "SIB-4471", coveragePercentage: 90, coverageLimit: 3000000, validUntil: "2027-03-31" }],
    createdBy: "Accueil - M. Diarra",
  },
  {
    id: "adm-004",
    admissionNumber: "ADM-2026-00838",
    patientId: "pat-1004",
    numeroPatient: "DOS-017455",
    patientName: "Kouadio Yao",
    sex: "M",
    age: 45,
    doctorName: "Dr. Céline Assi",
    department: "Chirurgie",
    admissionType: AdmissionType.OUTPATIENT,
    admissionStatus: AdmissionStatus.DISCHARGED,
    reason: "Consultation post-opératoire",
    admissionDate: "2026-08-16T11:20:00",
    actualDischarge: "2026-08-16T15:05:00",
    documents: [],
    companions: [],
    payers: [{ id: "p5", payerType: AdmissionPayerType.PATIENT, name: "Kouadio Yao", coveragePercentage: 100 }],
    createdBy: "Accueil - M. Diarra",
  },
  {
    id: "adm-005",
    admissionNumber: "ADM-2026-00835",
    patientId: "pat-1005",
    numeroPatient: "DOS-016980",
    patientName: "Awa Sanogo",
    sex: "F",
    age: 62,
    doctorName: "Dr. Fabrice N'Guessan",
    department: "Cardiologie",
    admissionType: AdmissionType.INPATIENT,
    admissionStatus: AdmissionStatus.TRANSFERED,
    reason: "Insuffisance cardiaque décompensée",
    admissionDate: "2026-08-14T13:10:00",
    documents: [],
    companions: [],
    payers: [{ id: "p6", payerType: AdmissionPayerType.INSURANCE, name: "NSIA", policyNumber: "NSIA-3320", coveragePercentage: 70, validUntil: "2026-11-30" }],
    createdBy: "Accueil - S. Ibaka",
  },
  {
    id: "adm-006",
    admissionNumber: "ADM-2026-00830",
    patientId: "pat-1006",
    numeroPatient: "DOS-016322",
    patientName: "Ibrahim Cissé",
    sex: "M",
    age: 39,
    doctorName: "Dr. Céline Assi",
    department: "Urgences",
    admissionType: AdmissionType.EMERGENCY,
    admissionStatus: AdmissionStatus.CANCELLED,
    reason: "Départ volontaire avant prise en charge",
    admissionDate: "2026-08-13T22:48:00",
    documents: [],
    companions: [],
    payers: [],
    createdBy: "Accueil - Nuit",
  },
];

export const getAdmissionById = (id: string) =>
  mockAdmissions.find((a) => a.id === id) ?? mockAdmissions[0];
