/**
 * Données de démonstration MPI.
 * À remplacer par les appels au Patient-Identity-Service
 * (search, get all, create, provisoir, regularisation, fusion…).
 */
import {
  AlertNiveau,
  AlertStatus,
  MotifProvisoire,
  Patient,
  SimilarityAlert,
  StatusDossier,
} from "../types";

export const mockPatients: Patient[] = [
  {
    id: "pat-1001",
    uniquePatientId: "NDPU-018245",
    nom: "Koffi",
    prenom: "Aya",
    age: 34,
    genre: "F",
    dateNaissance: "1992-03-14",
    lieuNaissance: "Abidjan",
    nomPere: "Koffi Bernard",
    nomMere: "Adjoua Marie",
    email: "aya.koffi@example.ci",
    numero: "+225 07 08 09 10 11",
    contactUrgence: "Jean Koffi — +225 05 55 44 33 22",
    numCMU: "CMU-99182",
    numIdentityNational: "CI-1992-0031487",
    statusDossier: StatusDossier.DEFINITIF,
    serviceCreation: "Accueil central",
    createdAt: "2024-01-12T09:00:00",
    archivDossier: [
      { id: "ad1", name: "cni_aya_koffi.pdf", typeDoc: "Pièce d'identité", extension: "pdf", size: "412 Ko", date: "2024-01-12T09:05:00" },
      { id: "ad2", name: "carte_cmu.jpg", typeDoc: "Carte CMU", extension: "jpg", size: "1.1 Mo", date: "2024-01-12T09:06:00" },
    ],
  },
  {
    id: "pat-1002",
    uniquePatientId: "NDPU-018246",
    nom: "Traoré",
    prenom: "Moussa",
    age: 58,
    genre: "M",
    dateNaissance: "1968-07-02",
    lieuNaissance: "Bouaké",
    numero: "+225 01 02 03 04 05",
    statusDossier: StatusDossier.PROVISOIRE,
    motifDossierProvisoire: MotifProvisoire.PATIENT_INCONSCIENT,
    serviceCreation: "Urgences",
    createdAt: "2026-08-18T09:42:00",
  },
  {
    id: "pat-1003",
    uniquePatientId: "NDPU-017903",
    nom: "Mensah",
    prenom: "Grace",
    age: 27,
    genre: "F",
    dateNaissance: "1999-11-20",
    lieuNaissance: "Yamoussoukro",
    email: "grace.mensah@example.ci",
    numero: "+225 07 77 66 55 44",
    numSecuSocial: "SS-4471-8890",
    statusDossier: StatusDossier.DEFINITIF,
    serviceCreation: "Maternité",
    createdAt: "2025-06-01T10:00:00",
  },
  {
    id: "pat-1004",
    uniquePatientId: "NDPU-017455",
    nom: "Yao",
    prenom: "Kouadio",
    age: 45,
    genre: "M",
    dateNaissance: "1981-02-09",
    numero: "+225 05 12 34 56 78",
    statusDossier: StatusDossier.DEFINITIF,
    serviceCreation: "Consultation",
    createdAt: "2023-09-15T14:00:00",
  },
  {
    id: "pat-1005",
    uniquePatientId: "NDPU-000042",
    nom: "Inconnu",
    prenom: "X",
    age: 0,
    genre: "M",
    statusDossier: StatusDossier.PROVISOIRE,
    motifDossierProvisoire: MotifProvisoire.IDENTITE_INCONNUE,
    serviceCreation: "Urgences",
    createdAt: "2026-08-18T02:15:00",
  },
];

export const getPatientById = (id: string) =>
  mockPatients.find((p) => p.id === id) ?? mockPatients[0];

export const mockAlerts: SimilarityAlert[] = [
  {
    id: "al-1",
    patientAId: "pat-1001",
    patientBId: "pat-1006",
    numeroDossierA: "NDPU-018245",
    numeroDossierB: "NDPU-018802",
    patientAName: "Aya Koffi",
    patientBName: "Aya Koffi",
    score: 94,
    niveau: AlertNiveau.FORTE,
    status: AlertStatus.EN_ATTENTE,
    detectedAt: "2026-08-18T04:00:00",
    matchedFields: [
      { field: "nom", score: 100 },
      { field: "prenom", score: 100 },
      { field: "dateNaissance", score: 100 },
      { field: "numero", score: 70 },
    ],
  },
  {
    id: "al-2",
    patientAId: "pat-1003",
    patientBId: "pat-1007",
    numeroDossierA: "NDPU-017903",
    numeroDossierB: "NDPU-017950",
    patientAName: "Grace Mensah",
    patientBName: "Grâce Mensa",
    score: 78,
    niveau: AlertNiveau.MODEREE,
    status: AlertStatus.EN_ATTENTE,
    detectedAt: "2026-08-17T04:00:00",
    matchedFields: [
      { field: "nom", score: 85 },
      { field: "prenom", score: 90 },
      { field: "dateNaissance", score: 100 },
      { field: "lieuNaissance", score: 60 },
    ],
  },
  {
    id: "al-3",
    patientAId: "pat-1004",
    patientBId: "pat-1008",
    numeroDossierA: "NDPU-017455",
    numeroDossierB: "NDPU-016320",
    patientAName: "Kouadio Yao",
    patientBName: "Kouadio Yoa",
    score: 72,
    niveau: AlertNiveau.MODEREE,
    status: AlertStatus.IGNOREE,
    detectedAt: "2026-08-15T04:00:00",
    matchedFields: [
      { field: "nom", score: 80 },
      { field: "prenom", score: 88 },
      { field: "numero", score: 50 },
    ],
  },
];
